@startuml
'https://plantuml.com/sequence-diagram

class Usuario {
    - cedula: long
    - nombreCompleto: String
    - telefono: long
    - email: String
    - contraseña: String
    - codigoActivacion: String
    - codigoContraseña: String
    - activado: boolean
}

enum TipoUsuario {
    ADMINISTRADOR
    CLIENTE
}

class Cliente extends Usuario {
    - billeteraCliente: Billetera
}

class Administrador extends Usuario {
}

class Alojamiento {
    - direccionAlojamiento: int
    - nombreAlojamiento: String
    - ciudades: List<Ciudad>
    - descripcionAlojamiento: String
    - imagenAlojamiento: String
    - precioPorNocheAlojamiento: double
    - capacidadMaximaAlojamiento: int
    - servicios: List<Servicio>
}

enum TipoAlojamiento {
    CASA
    APARTAMENTO
    HOTEL
}

class Casa extends Alojamiento {
    - AseoCasa: double
    - MantenimientoCasa: double
}

class Apartamento extends Alojamiento {
    - AseoApartamento: double
    - MantenimientoApartamento: double
}

class Hotel extends Alojamiento {
    - habitaciones: List<Habitacion>
}

class Habitacion {
    - numeroHabitacion: int
    - precioHabitacion: double
    - capacidadHabitacion: int
    - imagenHabitacion: String
    - descripcionHabitacion: String
}

class Billetera {
    - saldoBilletera: double
}

class Reserva {
    - clienteReserva: Cliente
    - alojamientoReserva: Alojamiento
    - fechaInicioReserva: Date
    - fechaFinReserva: Date
    - numHuespedesReserva: int
}

class Factura {
    - subTotalFactura: double
    - totalFactura: double
    - fechaFactura: Date
    - codigoFactura: UUID
}

class Oferta {
    - descripcionOferta: String
    - descuentoOferta: float
    - fechaInicioOferta: Date
    - fechaFinOferta: Date
}

class Estadistica {
    - ocupacionPorcentual: double
    - gananciasTotales: double
}

class Reseña {
    - cometarioReseña: String
    - calificacionReseña: float
}

class QR {
}

Cliente "1" --> "1" Billetera
Administrador "1" --> "many" Alojamiento
Cliente "1" --> "many" Reserva
Alojamiento "1" --> "many" Oferta
Alojamiento "1" --> "many" Reseña
Alojamiento "1" --> "many" Reserva
Reserva "1" --> "1" Factura
Factura "1" --> "1" QR
Hotel "1" --> "many" Habitacion

@enduml
